### ISSUE TITLE
contributing links to old GitHub repo

### ISSUE THREAD

**Issue by spdegabrielle** [7guis/7guis#22]
https://7guis.github.io/7guis/contributing

> Setup
>  Fork [the repo](https://github.com/eugenkiss/7guis)
>  Clone your fork

**Comment by dumblob** [comment]
Please make a PR, thanks!

**Comment by spdegabrielle** [comment]
No need to fork
The change is already made

https://github.com/7guis/7guis/blob/7d260aee0ff065de00193e63953cd71f6f8c4e19/site/src/containers/Contributing.js#L21

the site needs a rebuild

**Comment by dumblob** [comment]
Would you find some time to rebuild the site?

**Comment by spdegabrielle** [comment]
I sorry I’m not set up to rebuild the site in its current form. If I have to take over this task I would change how it is done so it is quick and easy for **me**. 

I don’t think anyone wants a change like that that so I’ll refrain and leave the task of rebuilding with another owner? 

@dumblob @tbreuss @mirohs if none of you are able to rebuild with minimal effort we should discuss a more maintainable approach.

**Comment by dumblob** [comment]
Yes, let us discuss it.

For my part:

1. I have very little time and thus it needs to be 100% automated (e.g. using GitHub CI).
2. I do not care about specific technology but strongly prefer something which the **majority** of both existing **and** potential contributers can handle.
3. I somewhat prefer things which do not break often - but it is nothing decisive for me nor anything I feel strongly about.

What about others?

**Comment by spdegabrielle** [comment]
@tbreuss @mirohs Gentle reminder

**Comment by tbreuss** [comment]
I'll try to fix this next week, I'm on holidays right now.

It seems, that there is a makefile for building the site.

https://github.com/7guis/7guis/blob/master/site/Makefile#L22

The makefile itself must be fixed of course. But in terms of the build process, everything's okay. 

Maybe we could optimize this a little, so that the build step is done automatically.

**Comment by tbreuss** [comment]
Since Hacktoberfest has just begun, and I'm willing to support this project and earn some hacktoberfest fame, I'm going to add a hacktoberfest tag to this repo and try to fix a few of the opened issues next week.

For more information about the Hacktoberfest challenge, see https://hacktoberfest.com.

**Comment by tbreuss** [comment]
This is fixed with a rebuild. I close this issue.

The pull request #26 with the edit still has to be reviewed and merged.
